### ISSUE TITLE
Thread 'main' panicked at 'Bad Request: can't parse entities

### ISSUE THREAD

**Issue by Antz0x0z** [avkviring/telegram-github-action#15]
Run avkviring/telegram-github-action@v0.0.8
/usr/bin/docker run --name d0729c12f3e5a5bdea436497326361106a5c36_7f6e8c --label d0729c --workdir /github/workspace --rm -e telegram_to -e telegram_token -e event -e INPUT_TELEGRAM_TO -e INPUT_TELEGRAM_TOKEN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/nft_private/nft_private":"/github/workspace" d0729c:12f3e5a5bdea436497326361106a5c36
**thread 'main' panicked at 'Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 630', src/telegram.rs:16:19**
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

![image](https://user-images.githubusercontent.com/47379684/102567457-2290d300-4114-11eb-9e5d-bb9936b1adcb.png)

/master/src/telegram.rs

    match result {
        Ok(result) => println!("{:?}", result),
        Err(e) => panic!("{}", e),
    };

**Comment by Antz0x0z** [comment]
@avkviring The process crashes 50% of the time. So I understand the problem in stability, and not in the logic of the component.

**Comment by avkviring** [comment]
Hi, It is depend on commit content. I will add some logs, and you can try again if you want.

**Comment by Antz0x0z** [comment]
@avkviring The commit contains the improvements and fixes of the Rust project (.rs) + part of the json commit of about a dozen files for 70 new lines of code. Yes. Add a debugger, let's check again.

**Comment by avkviring** [comment]
@Antz0x0z Please use avkviring/telegram-github-action@issues-15 for action.
