### ISSUE TITLE
Thread 'main' panicked at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by Antz0x0z** [avkviring/telegram-github-action#21]
During the execution of the job, an error started to occur: 
"thread 'main' panicked at 'called` Result :: unwrap () `on an` Err` value: ParseIntError {kind: InvalidDigit}', src / telegram.rs: 5: 73 "

![image](https://user-images.githubusercontent.com/47379684/112089364-1198a780-8bc4-11eb-8aac-62eb1d494a34.png)

The error began to appear after the bot connected to notifications in a private telegram channel, where chat_id begins with the prefix "-100...".

The problem is in the "chat" variable accepting negative unwrap as input:
let chat = ChatRef::from_chat_id(ChatId::new(chat_id.parse::<i64>().unwrap()));

**Comment by avkviring** [comment]
Hi,
ChatId::new(chat_id.parse::<i64>().unwrap());

i64 - it is signed integer.


InvalidDigit means:
```
Contains an invalid digit in its context.
Among other causes, this variant will be constructed when parsing a string that contains a non-ASCII char.
This variant is also constructed when a + or - is misplaced within a string either 
on its own or in the middle of a number.
```


I wrote small test, it is work.
```
let chat_id_string = "-100100".to_owned();
let chat_id = ChatId::new(chat_id_string.parse::<i64>().unwrap());
```
